### ISSUE TITLE
Incorporate `ruff` to format and check Python code

### ISSUE THREAD

**Issue by Yuan-Ru-Lin** [legend-exp/legend-dataflow-hades#4]
Use `ruff` to help formatting.

There has already been `.ruff.toml`. @ggmarshall did you think about it as well? What's your thought on this?

**Comment by ggmarshall** [comment]
The `ruff.toml` there is just the standard one we use in most of our repos for pre-commit from Luigi

**Comment by Yuan-Ru-Lin** [comment]
Closed by #5
